eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 90000.0
    expectedClientRenewalIntervalSeconds: 30
    renewalPercentThreshold: 0.85
server:
  port: 8761
spring:
  application:
    name: netflix.server
